language: ruby

git:
  depth: 10

os:
  - linux
  - osx

dist: xenial

rvm:
  - 2.6
  - 2.5

branches:
  only:
    - master

before_install:
  - gem update --system

install:
  - gem install jekyll jekyll-paginate jekyll-sitemap jemoji

script:
  - jekyll clean
  - jekyll build